title: Anastasov
email: ggeorgianastasov@gmail.com
description: hello
destination: docs

baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  # - .sass-cache/
  # - .jekyll-cache/
  # - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - gulpfile.js
  - .vscode